# By Abdullah As-Sadeed

YOLO_DEFAULT_CONFIDENCE = 40

MEDIAPIPE_DEFAULT_DETECTION_CONFIDENCE = 80
MEDIAPIPE_DEFAULT_TRACKING_CONFIDENCE = 50

MEDIAPIPE_DEFAULT_CONNECTION_COLOR = "#00FF00"
MEDIAPIPE_DEFAULT_CONNECTION_THICKNESS = 2
MEDIAPIPE_DEFAULT_CONNECTION_RADIUS = 8

MEDIAPIPE_DEFAULT_LANDMARK_COLOR = "#0000FF"
MEDIAPIPE_DEFAULT_LANDMARK_THICKNESS = 2

DEFAULT_WEBCAM_ID = 0

DEFAULT_VIDEO_WIDTH = 640
DEFAULT_VIDEO_HEIGHT = 480
