# By Abdullah As-Sadeed

name: Release
on:
  push:
    branches: ['main']
permissions:
      contents: read
      packages: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test
        run: |
          echo "Done!"

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            *
